ITAM-DS/analisis-numerico-computo-cientifico

MNO/entrega_tareas_de_C/tarea1/ollin/tarea_1_Ollin.c, MNO/entrega_tareas_de_C/tarea1/ollin/tarea_1_Ollin.txt
Incluye el archivo de C y un .txt con la salida y unas notas.
=> Primera tarea

MNO/entrega_tareas_de_C/tarea1/hatshex/tarea01_gabs.c, MNO/entrega_tareas_de_C/tarea1/hatshex/tarea01_gabs.txt
Subiendo la tarea 01 de Gabriela Flores Bracamontes, Clave de alumno 160124
=> Subiendo tarea 1 de Gabriela Flores Bracamontes

MNO/entrega_tareas_de_C/107882Tarea3/mnoTarea3.c, MNO/entrega_tareas_de_C/tarea2/walterMS/mnoTarea2.txt
=> Subiendo tarea2 de C

MNO/entrega_tareas_de_C/tarea4/96401/archivo.txt, MNO/entrega_tareas_de_C/tarea4/96401/archivo2.txt, MNO/entrega_tareas_de_C/tarea4/96401/ejecicio1.c, MNO/entrega_tareas_de_C/tarea4/96401/ejercicio_1_scanf.c, MNO/entrega_tareas_de_C/tarea4/96401/ejercicio_2_a.c, MNO/entrega_tareas_de_C/tarea4/96401/ejercicio_2_b.c, MNO/entrega_tareas_de_C/tarea4/96401/ejercicio_2_c.c, MNO/entrega_tareas_de_C/tarea4/96401/ejercicio_2_d.c, MNO/entrega_tareas_de_C/tarea4/96401/ejercicio_2_e.c, MNO/entrega_tareas_de_C/tarea4/96401/ejercicio_2_f.txt, MNO/entrega_tareas_de_C/tarea4/96401/ejercicio_3_a.c, MNO/entrega_tareas_de_C/tarea4/96401/ejercicio_3_b.c, MNO/entrega_tareas_de_C/tarea4/96401/ejercicio_4_a.c, MNO/entrega_tareas_de_C/tarea4/96401/ejercicio_4_b.c
=> Entrega tarea 4.

MNO/entrega_tareas_de_C/tarea4/114157/archivo1.txt, MNO/entrega_tareas_de_C/tarea4/114157/archivo2.txt, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_1.c, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_1_resultados.txt, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_2_resultados, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_2a.c, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_2b.c, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_2cyd.c, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_2e.c, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_3_resultados, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_3a.c, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_3b.c, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_4_resultados, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_4a.c, MNO/entrega_tareas_de_C/tarea4/114157/tarea4_4b.c
los resultados los puse en un txt para cada ejercicio
=> entrega de tarea 4

MNO/entrega_tareas_de_C/tarea4/116754/3b.c, MNO/entrega_tareas_de_C/tarea4/116754/Salidas.ipynb
Hola, estaba viendo el archivo de las tareas entregadas y veo que a varios les pides las salidas de sus programas así que recordé que no les puse a los míos. Al ver las salidas en el notebook vi que se estaba imprimiendo el espacio del inciso 3b así que agregué una línea.
=> Archivo de salidas

MNO/entrega_tareas_de_C/tarea5/114041/definiciones.h, MNO/entrega_tareas_de_C/tarea5/114041/definiciones2.h, MNO/entrega_tareas_de_C/tarea5/114041/funciones.c, MNO/entrega_tareas_de_C/tarea5/114041/funciones2.c, MNO/entrega_tareas_de_C/tarea5/114041/main.c, MNO/entrega_tareas_de_C/tarea5/114041/main2.c, MNO/entrega_tareas_de_C/tarea5/114041/tarea5.md
=> subimos la tarea 5

MNO/proyecto_final/MNO_2017/proyectos/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipo_7/avance_07_04_2017/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipo_7/avance_17_04_2017/README.md
Profe, editamos el README grupal para que los equipos aparecieran en orden.
=> update de los avances equipo 7

MNO/proyecto_final/MNO_2017/proyectos/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipo_6/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipo_6/avance_07_04_2017/README.md
Se actualiza README a nivel de proyectos tal como lo solicito Erick el 12 de Abril
=> Actualizando README

MNO/proyecto_final/MNO_2017/proyectos/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipo_9/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipo_9/avance_17_04_2017/README.md
=> comentarios a la estructura

MNO/proyecto_final/MNO_2017/proyectos/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipo_10/avance_17_04_2017/MPI_Distributed.md, MNO/proyecto_final/MNO_2017/proyectos/equipo_10/avance_17_04_2017/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipo_10/avance_17_04_2017/hello.sh, MNO/proyecto_final/MNO_2017/proyectos/equipo_10/avance_17_04_2017/hosts.sh, MNO/proyecto_final/MNO_2017/proyectos/equipo_10/avance_17_04_2017/installmpi.sh, MNO/proyecto_final/MNO_2017/proyectos/equipo_10/avance_17_04_2017/instancias, MNO/proyecto_final/MNO_2017/proyectos/equipo_10/avance_17_04_2017/setup_env.sh, MNO/proyecto_final/MNO_2017/proyectos/equipo_10/avance_17_04_2017/sourcefile
Van los avances de la segunda entrega
=> Avances Equipo 10 17-04-2017

MNO/proyecto_final/MNO_2017/proyectos/equipo_8/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipo_8/avance_19_04_2017/README.md
Actualizamos el README general del proyecto del equipo y agregamos los avances de la segunda entrega
=> Avances segunda entrega

C/extensiones_a_C/MPI/openMPI/Ubuntu_Dockerfile/Dockerfile
Hola Erick, este es una versión del Dockerfile para Ubuntu-MPI, creo que habías pedido que la versión. 
Está en una carpeta aislada, espero no te genere ningún conflicto.
Saludos!
=> Dockerfile MPI Ubuntu

MNO/proyecto_final/MNO_2017/proyectos/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipos/equipo_6/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipos/equipo_6/avance_02_05_2017/README.md
Realizamos Pull el día de hoy por que ayer estuvimos fuera de la ciudad.  Muchas gracias!
=> Avance 02_05_2017

MNO/proyecto_final/MNO_2017/proyectos/equipos/equipo_5/README.md, MNO/proyecto_final/MNO_2017/proyectos/equipos/equipo_5/avance_30_05_2017/README.md
Faltaba último README para reporte.
=> avance de la 2da semana de finales

entrega_tareas_de_C/tarea1/175897/tarea1.c, entrega_tareas_de_C/tarea1/175897/tarea1.txt
=> Subo Tarea1 C

entrega_tareas_de_C/tarea1/113032/tarea1_113032.c, entrega_tareas_de_C/tarea1/113032/tarea1_113032.txt
=> tarea1_113032

entrega_tareas_de_C/tarea2/109649/Respuestas.txt
Se entrega la Tarea 2 respondiendo a las 4 preguntas en un .txt
=> Respuestas Tarea2

entrega_tareas_de_C/tarea2/175897/tarea2_1.txt, entrega_tareas_de_C/tarea2/175897/tarea2_2.c, entrega_tareas_de_C/tarea2/175897/tarea2_3.c, entrega_tareas_de_C/tarea2/175897/tarea2_4.c
=> Subo tarea 2

entrega_tareas_de_C/tarea3/165352/respuestas.txt, entrega_tareas_de_C/tarea3/165352/tarea3.c
Subo archivos tarea3.c y respuestas.txt a carpeta
=> Subo tarea 3

entrega_tareas_de_C/tarea4/160668/archivo.txt, entrega_tareas_de_C/tarea4/160668/archivo2.txt, entrega_tareas_de_C/tarea4/160668/ejer1.c, entrega_tareas_de_C/tarea4/160668/ejer1_scanf.c, entrega_tareas_de_C/tarea4/160668/ejer_2_a.c, entrega_tareas_de_C/tarea4/160668/ejer_2_b.c, entrega_tareas_de_C/tarea4/160668/ejer_2_c.c, entrega_tareas_de_C/tarea4/160668/ejer_2_d.c, entrega_tareas_de_C/tarea4/160668/ejer_2_e.c, entrega_tareas_de_C/tarea4/160668/ejer_3_a.c, entrega_tareas_de_C/tarea4/160668/ejer_3_b.c, entrega_tareas_de_C/tarea4/160668/ejer_4_a.c, entrega_tareas_de_C/tarea4/160668/ejer_4_b.c
=> Tarea 4 160668

proyecto_final/proyectos/equipos/equipo_12/README.md
Subo la carpeta y RMD para el trabajo final
=> Trabajo final: RMD y carpeta

proyecto_final/proyectos/equipos/equipo_10/Avance_10_04_2017/README.md, proyecto_final/proyectos/equipos/equipo_10/README.md
=> avance 10_04_2018

proyecto_final/proyectos/equipos/equipo_8/README.md, proyecto_final/proyectos/equipos/equipo_8/avance_10_04_18/entrega1_1.md, proyecto_final/proyectos/equipos/equipo_8/avance_17_04_18/Cournot.py, proyecto_final/proyectos/equipos/equipo_8/avance_17_04_18/segunda_entrega.md
Realizamos los cambios que se nos pidieron y además se hacemos la entrega 2.
=> Segunda entrega Equipo 8

proyecto_final/proyectos/equipos/equipo_03/README.md, proyecto_final/proyectos/equipos/equipo_03/avance_17_04_2018/README.md
Subimos segundo avance del proyecto final con fecha 17_04_2018.
Se actualiza Readme de la carpeta del equipo con las Referencias.
=> Avance semana 17_04_2018

proyecto_final/proyectos/equipos/equipo_04/avance_17_04_2018/README.md, proyecto_final/proyectos/equipos/equipo_04/avance_17_04_2018/dev_array.h, proyecto_final/proyectos/equipos/equipo_04/avance_17_04_2018/kernel.cu, proyecto_final/proyectos/equipos/equipo_04/avance_17_04_2018/kernel.h, proyecto_final/proyectos/equipos/equipo_04/avance_17_04_2018/matrixmul.cu
Mi compañero Arturo González hizo pull request, 1 día retrasado, con el primer avance del proyecto. Por otra parte, en esta entrega mandamos un md con el avance 2 y los archivos complementarios de la implementación de una multiplicación de matrices en CUDA sobre la plataforma de AWSS2.
Saludos
=> Subimos avance 2 equipo 4

proyecto_final/proyectos/equipos/equipo_02/README.md, proyecto_final/proyectos/equipos/equipo_02/avance_17_04_2018/Readme.md, proyecto_final/proyectos/equipos/equipo_02/avance_17_04_2018/Referencias/Readme.md, proyecto_final/proyectos/equipos/equipo_02/avance_17_04_2018/implementacion/choleskyEjemplo.c
Se entrega la investigación teórica y un primer ejemplo de la implementación dle algoritmo para la factorización Cholesky, además de las referencias escritas con las que contamos y su enlace a ellas, enlace directo a la presentación y al trabajo escrito.
=> Avance 17/Abril

proyecto_final/proyectos/equipos/equipo_04/README.md
Envío Readme solicitado por correo.
=> Subo Readme solicitado

proyecto_final/proyectos/equipos/equipo_05/README.md, proyecto_final/proyectos/equipos/equipo_05/avance_07_04_2018/README.md, proyecto_final/proyectos/equipos/equipo_05/avance_17_04_2017/README.md, proyecto_final/proyectos/equipos/equipo_05/avance_24_04_2017/README.md
Se subió el avance correspondiente al día de hoy, así como el avance pasado, el cual se subió a destiempo. 
Con el fin de no saturar el repositorio.
El código permanece limpio en el repositorio balanceo de línea cuyo link se encuentra en los readme's de los avances.
Se le envió invitación a Erick.
=> Subida de avance.

proyecto_final/proyectos/equipos/equipo_04/README.md, proyecto_final/proyectos/equipos/equipo_04/avance_24_04_2018/README.md, proyecto_final/proyectos/equipos/equipo_04/avance_24_04_2018/ejercicio-imagen.py, proyecto_final/proyectos/equipos/equipo_04/avance_24_04_2018/grayscale.c, proyecto_final/proyectos/equipos/equipo_04/avance_24_04_2018/grayscale.cu, proyecto_final/proyectos/equipos/equipo_04/avance_24_04_2018/kernel.cu, proyecto_final/proyectos/equipos/equipo_04/avance_24_04_2018/kernel.h
=> Subo avance3 24/4/2018

proyecto_final/proyectos/equipos/equipo_02/README.md, proyecto_final/proyectos/equipos/equipo_02/avance_24_04_2018/Readme.md, proyecto_final/proyectos/equipos/equipo_02/avance_24_04_2018/implementación/filtro_kalman.c, proyecto_final/proyectos/equipos/equipo_02/avance_24_04_2018/implementación/readme.md
Se agrega al tercer avance una implementación del filtro de Kalman.
=> Tercer Avance Proyecto Final

proyecto_final/proyectos/equipos/equipo_8/README.md, proyecto_final/proyectos/equipos/equipo_8/avance_24_04_18/tercera_entrega.md
Hacemos tercera entrega. Se incluye link a carpeta de Dropbox con los avances del trabajo escrito.
=> Tercera entrega Equipo 8

proyecto_final/proyectos/equipos/equipo_6/avance_1_05_2018/README.md
Esta semana trabajamos sobre el proyecto escrito, e investigamos sobre la descomposición QR sus varaintes y estabilidad númerica. Posteriormente, investigamos un poco sobre la libreria MAGAMA.
=> avance_1_05_2018

proyecto_final/proyectos/equipos/equipo_02/README.md, proyecto_final/proyectos/equipos/equipo_02/avance_02_05_2018/Readme.md, proyecto_final/proyectos/equipos/equipo_02/avance_02_05_2018/implementacion/Readme.md, proyecto_final/proyectos/equipos/equipo_02/avance_02_05_2018/implementacion/cholesky.c, proyecto_final/proyectos/equipos/equipo_02/avance_02_05_2018/implementacion/verosim.c
Se adjunta el avance para el proyecto de Factorización Cholesky
=> Avance 2 de Mayo Equipo 2

proyecto_final/proyectos/equipos/equipo_8/README.md
Avance del dia 2 de mayo y liga dropbox
=> Actualizacion con la liga del dropbox

proyecto_final/proyectos/equipos/equipo_11/README.md, proyecto_final/proyectos/equipos/equipo_11/avance_01_05_18/codigo/README.md
Hola Erick, disculpa por la entrega, andabamos medio apurados y no nos pusimos bien de acuerdo. Thalia corrigio el pr que habia hecho y aparte para corregir otros de los problemas que comentabas hago este pr adicional. Gracias.
=> Correcciones al README de la carpeta principal, y agrego pruebas de ejecucion del avance 1 de mayo

proyecto_final/proyectos/equipos/equipo_12/avance_08_05_18/README.md, proyecto_final/proyectos/equipos/equipo_12/avance_15_05_18/Codigo/Readme.md, proyecto_final/proyectos/equipos/equipo_12/avance_15_05_18/Codigo/rand.sh, proyecto_final/proyectos/equipos/equipo_12/avance_15_05_18/DecimalToBinary_v2.c, proyecto_final/proyectos/equipos/equipo_12/avance_15_05_18/Readme.md
=> avance proyecto

proyecto_final/proyectos/equipos/equipo_02/avance_22_05_2018/Readme.md
Se commitea el avance del 22 de mayo
=> Avance 22-mayo

proyecto_final/proyectos/equipos/equipo_12/README.md, proyecto_final/proyectos/equipos/equipo_12/avance_30_05_18/Readme.md
Mando el Trabajo Final del equipo 12
Saludos!
=> Trabajo Final 12

proyecto_final/proyectos/equipos/equipo_8/README.md
=> Update de presentación

proyecto_final/proyectos/equipos/equipo_8/README.md
=> Update de README.md

proyecto_final/proyectos/equipos/equipo_03/avance_final/README.md
En el Readme del avance final se incluyen las instrucciones de la implementación final
=> Agrega instrucciones a Readme

proyecto_final/proyectos/equipos/equipo_6/README.md
En un momento más mandamos el commit del repo de Mario para que veas el código final
=> Mno 2018 1

proyecto_final/proyectos/equipos/equipo_2/README.md, proyecto_final/proyectos/equipos/equipo_2/avance_1/README.md
=> Mno 2019 1

proyecto_final/proyectos/equipos/equipo_9/avance_2/README.md, proyecto_final/proyectos/equipos/equipo_9/avance_2/agenda.md, proyecto_final/proyectos/equipos/equipo_9/avance_3/README.md, proyecto_final/proyectos/equipos/equipo_9/avance_3/agenda.md, proyecto_final/proyectos/equipos/equipo_9/avance_3/proyecto-final.tex, proyecto_final/proyectos/equipos/equipo_9/src/estimacion_parametros_edp.Rmd, proyecto_final/proyectos/equipos/equipo_9/src/implementacion_paro.Rmd, proyecto_final/proyectos/equipos/equipo_9/src/mno_regresiones.Rmd
Erick, para tu consideración.
Es válido hacer merges para cada avance; o bien esperamos hasta el final?
Saludos,
JA, AV, EM
=> PR Equipo 9 - Avance 2 

proyecto_final/proyectos/equipos/equipo_2/avance_2/README.md
se suben actividades, falta ordenar carpeta de código para subir
=> segundo avance

proyecto_final/proyectos/equipos/equipo_10/README.md
Se adicionó la liga a nuestro trabajo escrito para el proyecto final.
=> Liga al trabajo escrito

proyecto_final/proyectos/equipos/equipo_3/README.md, proyecto_final/proyectos/equipos/equipo_3/avance_6/Implementación Proyecto - Equipo 3.Rmd, proyecto_final/proyectos/equipos/equipo_3/avance_6/README.md
Versión Final Implementación y Presentación
=> Equipo 3 - Avance 6

proyecto_final/proyectos/equipos/equipo_11/README.md
Se adjunta la liga con los entregables finales
=> Entregables Final

proyecto_final/proyectos/equipos/equipo_12/Entregable_Final_Proyecto/README.md, proyecto_final/proyectos/equipos/equipo_12/Entregable_Final_Proyecto/implementacion_codigos/Analisis_Exploratorio.Rmd, proyecto_final/proyectos/equipos/equipo_12/Entregable_Final_Proyecto/implementacion_codigos/BSM_NewtonRaphson.Rmd, proyecto_final/proyectos/equipos/equipo_12/Entregable_Final_Proyecto/implementacion_codigos/Garch_DescensoGradiente.Rmd, proyecto_final/proyectos/equipos/equipo_12/Entregable_Final_Proyecto/implementacion_codigos/GramCharlier_DescensoGradiente.Rmd, proyecto_final/proyectos/equipos/equipo_12/Entregable_Final_Proyecto/implementacion_codigos/README.md
Actualizaciones del entregable final del proyecto.
=> Entrega Final 

proyecto_final/proyectos/equipos/equipo_11/README.md
Se adjunta la liga directa a la implementación
=> Liga Implementación

proyecto_final/proyectos/equipos/equipo_5_y_9/avance1/README.md
Se agrega copia de reporte avance1 del Proyecto Final de equipos 5 y 9.
El reporte original presentado al profesor el 9 de mayo, también se encuentra disponible en:
https://github.com/DorelyMS/proyecto-final-equipo5-mno-2020-1/blob/master/Avances/Avance1/README.md
=> Se añade reporte avance1 de equipos 5 y 9

proyecto_final/proyectos/equipos/equipo_5_y_9/avance2/README.md
Se agrega copia de reporte avance2 del Proyecto Final de equipos 5 y 9.
El reporte original, también se encuentra disponible en:
https://github.com/DorelyMS/proyecto-final-equipo5-mno-2020-1/blob/master/Avances/Avance2/README.md
=> Se añade reporte avance2 de equipos 5 y 9

proyecto_final/proyectos/equipos/equipos_6_y_8/README.md, proyecto_final/proyectos/equipos/equipos_6_y_8/avance4/README.md
Se añade avance final de los equipos 6 y 8
=> añadiendo avance equipos 6 y 8

proyecto_final/proyectos/equipos/equipo_4/README.md
Agregando carpeta para Equipo 4, proyecto PageRank.
=> Agregando carpeta para Equipo 4

proyecto_final/proyectos/equipos/equipo_2/README.md
Liga al repo del proyecto final para el equipo 2.
Se ajustó pull request a la rama del curso.
=> Liga al repo del proyecto final para el equipo 2

proyecto_final/proyectos/equipos/equipo_2/README.md
Se realizan ajustes en la edición para mayor comprensión del problema a tratar
=> Ajustes de edición

proyecto_final/proyectos/equipos/equipo_2/README.md
Estimación de probabilidades de incumplimiento, proyecto final de la materia de optimizacion
=> Entregable final equipo 2

proyecto_final/proyectos/equipos/equipo_2/utils/README.md, proyecto_final/proyectos/equipos/equipo_2/utils/utils.py
Proyecto final para el equipo 2 incluyendo código de optimización para resolver los dos problemas planteados.
=> Optimizacion 2020 2

proyecto_final/proyectos/equipos/equipo_4/README.md
README para el informe y elementos del proyecto final del equipo 4.
=> Equipo 4 -  Adds README

proyecto_final/proyectos/equipos/equipo_3/README.md
Actualizacion de reporte escrito, presentacion, reporte de resultados y liga de implementacion
=> Actualizacion de vinculos para entrega final

proyecto_final/proyectos/equipos/equipo_4/avance2.md
También se deja listo el desarollo de código.
=> Agregamos avance 2, donde se implementan avances al reporte.

proyecto_final/proyectos/equipos/equipo_4/avance3.md
Hola Erick :) 
Ya completamos el reporte del proyecto (el cuál puedes encontrar en la carpeta Reporte), sólo nos falta agregar la liga a la presentación.
=> Tercer avance

proyecto_final/proyectos/equipos/equipo_8/README.md, proyecto_final/proyectos/equipos/equipo_8/avance1/README.md
Hola profe @palmoreck, 
En este pull request actualizamos la información de nuestro proyecto con el tema, los objetivos y la liga al repo. También creamos toda una carpeta donde detallamos nuestro Avance 1.
=> Información del equipo 8 y primer avance

proyecto_final/proyectos/equipos/equipo_6/README.md, proyecto_final/proyectos/equipos/equipo_6/avance_1/README.md
=> agrega descripcion de proyecto y avance 1 equipo 6

proyecto_final/proyectos/equipos/equipo_1/README.md
Se actualiza el README que se despliega para nuestro equipo.
Se sigue el formato ejemplo.
Faltaría agregar enlaces.
=> Actualizando README del equipo 1

proyecto_final/proyectos/equipos/equipo_1/avance1/avance1.md
Se agrega lo correspondiente al Avance 1 de nuestro proyecto:
- Se crea carpeta llamada "Avance1".
- Se crea archivo ".md" llamado "avance1.md" donde se desarrolla lo hecho para esta iteración.
=> Agregando AVANCE1

proyecto_final/proyectos/equipos/equipo_1/Avance2/avance2.md
Se agrega lo correspondiente al Avance 2 de nuestro proyecto:
- Se crea carpeta llamada "Avance2".
- Se crea archivo ".md" llamado "avance2.md" donde se desarrolla lo hecho para esta iteración.
=> Agregando AVANCE2

proyecto_final/proyectos/equipos/equipo_3/README.md
=> Optimizacion 2021

proyecto_final/proyectos/equipos/equipo_4/README.md
como está en el repo. Agregamos ligas a los folders pertinentes y una descripción general del objetivo del proyecto.
=> Subimos el README del proyecto,

proyecto_final/proyectos/equipos/equipo_1/README.md
- Se agrega el enlace de nuestra presentación en el README.
=> Actualizando README con enlace a la presentación

proyecto_final/proyectos/equipos/equipo_1/avance3/avance3.md
- Se crea la carpeta de nuestros "avances3".
- Dentro de la carpeta se agrega el archivo *markdown* que contiene lo hecho en esta tercera iteración.
- Se amplian las referencias de iteraciones anteriores.
=> Agregando avances3

proyecto_final/proyectos/equipos/equipo_1/README.md
- Se actualizan las referencias del README.
- Se agregan 2 referencias más.
=> Actualización de referencias README

proyecto_final/proyectos/equipos/equipo_1/avance1/avance1.md
- Se actualizan las referencias.
- Se agregan 2 referencias más.
=> Actualización referencias AVANCES1

proyecto_final/proyectos/equipos/equipo_1/Avance2/avance2.md
- Se actualizan las referencias.
- Se agregan 2 referencias más.
=> Actualización referencias AVENCES3

proyecto_final/proyectos/equipos/equipo_6/avance_2/README.md
Atendimos a los comentarios que fueron dejados en Canvas
Esta versión debe verse aún como preliminar, ya que aún no se contaba con resultados definitivos al realizarse
=> avance 2 equipo 6: correcciones al trabajo escrito

proyecto_final/proyectos/equipos/equipo_3/README.md
nombres de archivos sin acentos
=> se actualiza liga de acceso a la presentación

proyecto_final/proyectos/equipos/equipo_1/README.md
Se actualizan ligas de presentación y reporte final a nuestro repo.
=> Actualizando rutas de presentacion y reporte final
